Feature #add issue temp
AmazingAng/WTF-Solidity pull request #686
Opened 2024-03-20 03:13 UTC by fuchanghai

### What type of PR is this (这是什么类型的PR)

- [ ] Typo(勘误)
- [ ] BUG(程序错误)
- [ ] Improvement(提升)
- [ ] Feature(新特性)

### Which issue(s) this PR fixes(Optional) (这个PR 修复了什么问题 (可选择))

* resolve(修复) : #

### What this PR does / why we need it (这个PR 做了什么/ 我们为什么需要这个PR)

2024-03-20 03:15 UTC, fuchanghai commented
@AdamZeng1 @XdpCs  看一下这种模版行不行

2024-03-20 03:22 UTC, fuchanghai commented
效果如下
- bug
<img width="1162" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/33984497/ae0d8d2c-d516-400a-b4bf-5361ac0f6845">

- doc

<img width="1249" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/33984497/57ed2cc5-775e-4f7b-910f-d454c7772454">

- improve
<img width="1179" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/33984497/67ac6ec3-af94-4d20-99a0-7f6569fff281">
- faq
<img width="1439" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/33984497/3ed158c0-3d05-46e9-ae9c-b212747b8596">

2024-03-21 14:20 UTC, XdpCs commented
从使用体验上 确实比我合并进去的那个要好

2024-03-21 23:25 UTC, XdpCs commented
有些地方是否过于口语化了

2024-03-21 23:26 UTC, XdpCs commented
> @AdamZeng1 @XdpCs  看一下这种模版行不行

能否按照现有的模版的文案改改

2024-03-22 01:30 UTC, XdpCs commented
@fuchanghai 
https://github.com/AmazingAng/WTF-Solidity/tree/main/.github/ISSUE_TEMPLATE
大佬是否有空参考一下 这里面的翻译 然后修改一下你的

2024-03-22 02:05 UTC, fuchanghai commented
> @fuchanghai https://github.com/AmazingAng/WTF-Solidity/tree/main/.github/ISSUE_TEMPLATE 大佬是否有空参考一下 这里面的翻译 然后修改一下你的

hi 
@XdpCs  大佬是这样子的，我接触过的apache 项目以及一些开源项目都是description 和 anything else。当然社区大于规则，我接受 [code of conduct](https://www.apache.org/foundation/policies/conduct),目前可能review 的就我们三个，我是+1，您是request change, 我想看看 @AmazingAng 的想法，我最终会按投票结果来确认如何修改

2024-03-22 15:33 UTC, AmazingAng commented
整体挺棒的，不过我觉得需要简化一些，不能照搬 Apache 的。

因为咱们repo是教程，不像开源软件有不同版本。

2024-03-23 02:45 UTC, fuchanghai commented
> 整体挺棒的，不过我觉得需要简化一些，不能照搬 Apache 的。
> 
> 因为咱们repo是教程，不像开源软件有不同版本。

好的 @AmazingAng  那我按照 @XdpCs 的模版来弄吗？ cc @XdpCs

2024-03-26 08:25 UTC, XdpCs commented
> > 整体挺棒的，不过我觉得需要简化一些，不能照搬 Apache 的。
> > 因为咱们repo是教程，不像开源软件有不同版本。
> 
> 好的 @AmazingAng 那我按照 @XdpCs 的模版来弄吗？ cc @XdpCs

我觉得可行

2024-03-27 09:24 UTC, fuchanghai commented
> > > 整体挺棒的，不过我觉得需要简化一些，不能照搬 Apache 的。
> > > 因为咱们repo是教程，不像开源软件有不同版本。
> > 
> > 
> > 好的 @AmazingAng 那我按照 @XdpCs 的模版来弄吗？ cc @XdpCs
> 
> 我觉得可行 @fuchanghai

@AmazingAng

2024-03-27 09:47 UTC, AmazingAng commented
可以的

2024-03-28 05:12 UTC, fuchanghai commented
@AmazingAng done .PTAL cc @XdpCs

2024-03-28 09:30 UTC, XdpCs requested changes

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: Describe what happened.(描述一下发生了啥)
这个口语化的东西 可以改一下吗
例如 改成了 “发生了什么”

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Ask a question or request support for using WTF-Solidity
缺少中文翻译

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      value: "Thanks for completing our form!"
缺少中文翻译

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/document.yml
> +        能用英文用英文，觉得描述不清就用中文
缺少英文

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/document.yml
> +      value: "Thanks for completing our form!"
缺少中文

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        能用英文用英文，觉得描述不清就用中文
缺少英文

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      value: "Thanks for completing our form!"
缺少中文

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/improvement-report.yml
> +        能用英文用英文，觉得描述不清就用中文
缺少英文

2024-03-28 09:30 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/improvement-report.yml
> +      value: "Thanks for completing our form!"
缺少中文

2024-03-28 12:03 UTC, XdpCs requested changes

2024-03-28 12:03 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Ask a question or request support for using WTF-Solidity （提个在使用WTF-Solidity时遇到的问题或者获得支持）
是否可以改成 "在使用WTF-Solidity时，遇到的问题或者需要获得帮助"

2024-03-28 12:03 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/document.yml
> +        （为了更好的全球化的交流，能用英文用英文，觉得描述不清就用中文）
是否可以改成"为了更好的全球化的交流，能使用英文，尽量使用英文，如果觉得用英文无法清楚描述，可以使用中文"

2024-03-28 12:03 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        （为了更好的全球化的交流，能用英文用英文，觉得描述不清就用中文）
是否可以改成"为了更好的全球化的交流，能使用英文，尽量使用英文，如果觉得用英文无法清楚描述，可以使用中文"

2024-03-28 12:03 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/improvement-report.yml
> +        If you feel the description in English is not clear, then you can use Chinese, thanks!
是否可以改成"为了更好的全球化的交流，能使用英文，尽量使用英文，如果觉得用英文无法清楚描述，可以使用中文"

2024-04-02 00:45 UTC, XdpCs commented
@fuchanghai 大佬有空修改一下

2024-04-07 03:06 UTC, fuchanghai commented
done @XdpCs

2024-04-07 05:50 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/improvement-report.yml
> +        If you feel the description in English is not clear, then you can use Chinese, thanks!
@fuchanghai 这个还是没修改

2024-04-07 05:54 UTC, fuchanghai commented on .github/ISSUE_TEMPLATE/improvement-report.yml
> +        If you feel the description in English is not clear, then you can use Chinese, thanks!
![image](https://github.com/AmazingAng/WTF-Solidity/assets/33984497/76fa7815-25d3-4de9-a735-95d056a32ca6)

2024-04-08 08:59 UTC, XdpCs requested changes

2024-04-08 08:59 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      value: "Thanks for completing our form!"
@fuchanghai 这个没修改

2024-04-08 09:04 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +description: Problems and issues with code of WTF (报告WTF-Solidity中的程序Bug)
@fuchanghai 大佬是不是改反了

2024-04-08 09:10 UTC, XdpCs requested changes

2024-04-08 09:10 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +title: "[Bug] [Class (章节)] Bug title （标题）"
Bug title 这个翻译有问题

2024-04-08 09:10 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/document.yml
> +title: "[Doc][Module Name（模块）] Documentation bug or improvement（标题）"
Documentation bug or improvement 这个翻译有问题

2024-04-08 09:10 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +title: "[Feature][Module Name（模块名称）] Feature title（标题）"
Feature title 这个翻译有问题

2024-04-08 09:10 UTC, XdpCs commented on .github/ISSUE_TEMPLATE/improvement-report.yml
> +title: "[Improvement][Module Name（模块）] Improvement title（标题）"
这个标题有问题

2024-04-08 09:11 UTC, fuchanghai commented
> @fuchanghai @AmazingAng 我在想这种大的pr 是否可以直接使用squash and merge的形式
hi @XdpCs  个人的观点来看，每个pr 都应该用这种模式，一个pr 应该只能算一次commit，否则回滚cherry-pick 等操作不好做，太散了 cc @AmazingAng 
![image](https://github.com/AmazingAng/WTF-Solidity/assets/33984497/bad8e492-ee93-4c02-ae7c-73ad8362dd22)

2024-04-08 09:12 UTC, fuchanghai commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +title: "[Bug] [Class (章节)] Bug title （标题）"
这个统一都是标题吧

2024-04-08 09:15 UTC, XdpCs commented
> > @fuchanghai @AmazingAng 我在想这种大的pr 是否可以直接使用squash and merge的形式
> > hi @XdpCs  个人的观点来看，每个pr 都应该用这种模式，一个pr 应该只能算一次commit，否则回滚cherry-pick 等操作不好做，太散了 cc @AmazingAng
> > ![image](https://private-user-images.githubusercontent.com/33984497/320422110-bad8e492-ee93-4c02-ae7c-73ad8362dd22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Njc5NjYsIm5iZiI6MTcxMjU2NzY2NiwicGF0aCI6Ii8zMzk4NDQ5Ny8zMjA0MjIxMTAtYmFkOGU0OTItZWU5My00YzAyLWFlN2MtNzNhZDgzNjJkZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA5MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOTFjZGE1NjI5N2M0ZjkwZTczOWQ5YzYyMjQ0ZTE1MjY5MTk0NThmYWQ2MDZiZDc1MWIxOGY4NWUzNDhlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLGj_YUOsYInrA1Ch_5tuUCMnzZzancdRWJsDVgMkGY)

@fuchanghai 我的问题 我忘记回溯上面的comment了

2024-04-08 09:17 UTC, XdpCs commented
@fuchanghai title这个单词是否能大写统一一下 这一次改完 我就approve了 辛苦大佬了

2024-04-08 09:20 UTC, fuchanghai commented
> @fuchanghai title这个单词是否能大写统一一下 这一次改完 我就approve了 辛苦大佬了

done ,thanks for you review

2024-04-08 09:24 UTC, XdpCs approved these changes
@AmazingAng a大再reivew一下

2024-04-08 09:41 UTC, XdpCs commented
> > @fuchanghai @AmazingAng 我在想这种大的pr 是否可以直接使用squash and merge的形式
> > hi @XdpCs  个人的观点来看，每个pr 都应该用这种模式，一个pr 应该只能算一次commit，否则回滚cherry-pick 等操作不好做，太散了 cc @AmazingAng
> > ![image](https://private-user-images.githubusercontent.com/33984497/320422110-bad8e492-ee93-4c02-ae7c-73ad8362dd22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Njk1NzIsIm5iZiI6MTcxMjU2OTI3MiwicGF0aCI6Ii8zMzk4NDQ5Ny8zMjA0MjIxMTAtYmFkOGU0OTItZWU5My00YzAyLWFlN2MtNzNhZDgzNjJkZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA5NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYmYyYjlhZWE0ZDk5YjE4Y2FiNDZiNjRkNjA3MTdiNDgyMGNmMDBiYjBmOThkNmUyOGY3NTA5NjBhNWFlMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMLXWqorrISr7dwRw7wyeNTYDAq4EAx2NGfAyQXuYjQ)

这一点还需要a大定夺一下

2024-04-22 06:33 UTC, fuchanghai commented
@AmazingAng PTAL

2024-05-12 07:12 UTC, merged

2024-05-12 07:12 UTC, AmazingAng commented
lgtm