remove Address.sol, replace isContract with address(...).code.length > 0
AmazingAng/WTF-Solidity pull request #817
Opened 2024-10-17 09:09 UTC by eddiehsu66

### What type of PR is this (这是什么类型的PR)

- [x] Typo(勘误)
- [ ] BUG(程序错误)
- [ ] Improvement(提升)
- [ ] Feature(新特性)

### Which issue(s) this PR fixes(Optional) (这个PR 修复了什么问题 (可选择))

* resolve(修复) : # remove Address.sol, replace isContract with address(...).code.length > 0

### What this PR does / why we need it (这个PR 做了什么/ 我们为什么需要这个PR)
to.isContract()报错

2024-10-17 09:12 UTC, eddiehsu66 commented
不小心把远程仓库的分支删了，得亏本地还有，lol

2024-11-07 02:56 UTC, XdpCs requested changes

2024-11-07 02:56 UTC, XdpCs commented on 40_ERC1155/ERC1155.sol
> -    using Strings for uint256; // 使用Strings库
这行不应该删除，会导致编译失败

2024-11-07 02:56 UTC, XdpCs commented on 40_ERC1155/ERC1155.sol
> +                        revert(add(32, reason), mload(reason))
内联汇编是否可以修改成可读性更高的

2024-11-07 03:01 UTC, XdpCs commented
如果大佬没空修改的话，明天我会在你这个分支上修改完，进行合并

2024-11-10 10:37 UTC, XdpCs commented
> 这个我回退一下版本就行，是merge Main的时候导致的错误，至于内联汇编哪里，我主要参考的是[https://github.com/AmazingAng/WTF-Solidity/blob/main/34_ERC721/ERC721.sol](url) 的实现 这个remove Address.sol也是因为34节的Address.sol找不到的缘故，估计是前面的某个PR被合并后，而40节却忘了修改的缘故。

好的 辛苦了 我最近比较忙

2025-07-06 12:42 UTC, XdpCs approved these changes

2025-07-06 12:45 UTC, merged

2025-07-06 12:49 UTC, XdpCs commented
@eddiehsu66 拖了这么久 不好意思 这段时间太忙了